# -*- coding: utf-8 -*-
"""TF2.0 Installing Tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNKjrL5nEyvRN0MYrGYFLzHSJENaJXI1
"""

# What's already installed?
# import tensorflow as tf
# print(tf.__version__)

# Install TensorFlow 2.0
# You can run regular shell commands by prepending !
# !pip install -q tensorflow==2.0.0-beta1

# GPU version
# !pip install -q tensorflow-gpu==2.0.0-beta1

# Commented out IPython magic to ensure Python compatibility.
##### UPDATE 2020 #####
# new feature of colab - you can just use this
try:
#   %tensorflow_version 2.x  # Colab only.
except Exception:
  pass

# Check Tensorflow version again
import tensorflow as tf
print(tf.__version__)

# How to install a library permanently?
# https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab

# More fun with !
!ls

# More fun with !
# Nice! Looks like we already have some useful data to work with
!ls sample_data