# -*- coding: utf-8 -*-
"""TF2.0 Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jUk1HbNQnuz6JNY_X0cQoQXQic_rjqNC
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10*np.pi, 1000)
y = np.sin(x)

plt.plot(x,y)

"""# This is my title

Here is some regular text.



```
import numpy as np
```


"""

import sklearn
print(sklearn.__version__)
import numpy
print(numpy.__version__)
import scipy
print(scipy.__version__)
import matplotlib
print(matplotlib.__version__)
import pandas
print(pandas.__version__)
import torch
print(torch.__version__)
import seaborn
print(seaborn.__version__)
import wordcloud
print(wordcloud.__version__)
import bs4
print(bs4.__version__)
import requests
print(requests.__version__)
import theano
print(theano.__version__)
import networkx
print(networkx.__version__)
import cv2
print(cv2.__version__)
import gym
print(gym.__version__)

!ls

!ls sample_data

import json
json.loads(open('sample_data/anscombe.json').read())

a = 5

print(a)